### ISSUE TITLE
Patch conflict for nginx 1.13.6 ?

### ISSUE THREAD

**Issue by ClayMoreBoy** [kn007/patch#1]
![_20180330031437](https://user-images.githubusercontent.com/6189207/38108801-92f78154-33c8-11e8-9d02-f893d82758b8.png)

**Comment by kn007** [comment]
nginx每个版本都不一样的。patch不可能兼顾所有版本，除非原始代码一直变动不大。


你可以查看旧commit获得旧版本支持。

1.13.6，你可以用这个commit：
https://github.com/kn007/patch/blob/86694699185ab10d44167aa12a0086118016e57b/nginx.patch
