### ISSUE TITLE
想请教大佬nginx_with_quic.patch的用法和配置说明

### ISSUE THREAD

**Issue by dusk-sonw** [kn007/patch#14]
大佬这个patch应该是首个nginx实现http3的修改包了。
想请教您的用法和配置说明。

谢谢！

**Comment by kn007** [comment]
https://github.com/kn007/patch/commit/1cdff780bad0b0e98373fa50d0c35f0d6ba84322
提交记录里面有网址，这是整合了CF的patch。

你也可以通过以下链接访问，得到更多信息。
https://blog.cloudflare.com/experiment-with-http-3-using-nginx-and-quiche/

**Comment by giuem** [comment]
可以参考这个 https://github.com/giuem/nginx-giuem/tree/http-3 

Ubuntu 18.04 测试通过，16.04 和 centos 因为软件包版本较旧，需要手动编译新版本

**Comment by kn007** [comment]
补充即便是 centos 8 也一样需要编译。（
