### ISSUE TITLE
Can i use it for nginx 1.17.5-1.17.6 without any code changes to nginx_with_quic.patch ?

### ISSUE THREAD

**Issue by nailarch** [kn007/patch#15]
First of all thanks for your great work. ;)
I use it with https://github.com/angristan/nginx-autoinstall 

1.17.5-1.17.6 versions of nginx has some Bugfixes.
Can we use patch for nginx 1.17.5-1.17.6 without any code changes to nginx_with_quic.patch ?

**Comment by lazerl0rd** [comment]
@nailarch you can use the patches from https://github.com/lazerl0rd/nginx for mainline.
