### ISSUE TITLE
Upgrade quiche-nginx patch?

### ISSUE THREAD

**Issue by CarterLi** [kn007/patch#19]
https://github.com/cloudflare/quiche/commit/6d070ed8694216806f3ce689d71ceb7ad76d425e#diff-0a2594990fb2a0113e51e0f8fc7288b8a8ad83a6da946ee7995224ebaa101cef

BTW it's said that [quiche supports 0-RTT QUIC connection resumption now](https://github.com/cloudflare/quiche/tree/master/extras/nginx#0-rtt)

**Comment by kn007** [comment]
Updated.

**Comment by kn007** [comment]
test failed, fix later

**Comment by kn007** [comment]
test pass with 1.21.0
