### ISSUE TITLE
Pass connection RTT from quiche to nginx variable

### ISSUE THREAD

**Issue by sergey-v9** [kn007/patch#21]
Any plans to add a $tcpinfo_ analogue in nginx_with_quic.patch?

In my use case I'm passing an RTT value of the each client to the upstream:
`nginx.conf`
```
proxy_set_header        X-TCP-RTT              $tcpinfo_rtt;
```

It looks like quiche has some similar stats:

https://github.com/cloudflare/quiche/blob/92dcc500462ac22bb72e822d3f4e99039d29acfd/src/ffi.rs#L1000-L1034

I am a bit confused of how it can be passed from quiche to nginx variable. Could you help?

https://github.com/nginx/nginx/blob/e56ba23158b8466d108fd4d571bd7d9a88f2a473/src/http/ngx_http_variables.c#L1100-L1148

**Comment by kn007** [comment]
Sorry, I'm afraid that I can't.
