### ISSUE TITLE
nginx h3 patch not forward post context to upstream

### ISSUE THREAD

**Issue by calvin2021y** [kn007/patch#23]
Nginx  1.21.4 build with nginx_with_quic.patch,   and I add $request_body into nginx log.

I can see the nginx accept the request body, but upstream request_body is empty.

I can see the protocol is h3 from browser.  

Turn on/off ssl_dyn_rec_enable not help.

Remove this fix the bugs:
```conf
 listen 443 quic;
add_header alt-svc 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400';
```

**Comment by calvin2021y** [comment]
@kn007 any comment ?

**Comment by kn007** [comment]
pls open issue to quiche

**Comment by calvin2021y** [comment]
Assume the issue is cause by quiche not the patch provide by this project, let it open so people know there is a such issue will be helpful for some one actually use this project.
