### ISSUE TITLE
quiche with latest boringssl

### ISSUE THREAD

**Issue by gaby64** [kn007/patch#24]
I had to make some changes to get it compiling with the latest boringssl.

The quiche deps boringssl folder is empty even with doing git submodule --init, I do this instead:

```
rm -rf quiche/deps
mkdir quiche/deps
cd quiche/deps
git clone https://github.com/google/boringssl.git
```

nginx_with_quic.patch
``` nginx_with_quic.patch
+       mkdir -p $OPENSSL/build $OPENSSL/.openssl/lib $OPENSSL/.openssl/include/openssl \\
+       && cd $OPENSSL/build \\
+       && cmake -DCMAKE_C_FLAGS="$OPENSSL_OPT" -DCMAKE_CXX_FLAGS="$OPENSSL_OPT -Wno-stringop-overread" .. \\
+       && \$(MAKE) VERBOSE=1 \\
+       && cd .. \\
+       && cp -r include/openssl/*.h .openssl/include/openssl \\
+       && cp build/ssl/libssl.a build/crypto/libcrypto.a .openssl/lib
```

when I enable quic, all my php requests error 500, in the logs it says:
`[alert] 3924644#3924644: *5 epoll_ctl(1, 14) failed (17: File exists)`

**Comment by kn007** [comment]
Actually, you need to create an issue in cloudflare/quiche.

You could try using its patch with the latest boringssl for testing first.
