### ISSUE TITLE
Please adapt TLS dynamic records patch for 1.23.1 from QUIC branch

### ISSUE THREAD

**Issue by ammnt** [kn007/patch#25]
Hello,

can you please adapt nginx.patch (HTTP2 HPACK Encoding Support and Dynamic TLS Record)? For 1.23.1 version from QUIC branch:
https://hg.nginx.org/nginx-quic

Thank you.
Best regards🤭

**Comment by Karewan** [comment]
Hi,
I am also very interested to have this patch.
BR :)

**Comment by konkhra** [comment]
I am also interested!

**Comment by kn007** [comment]
https://github.com/kn007/patch/blob/master/nginx_1.25.0.patch
[9d7ffc4](https://github.com/kn007/patch/commit/9d7ffc48df81d9595556cf527bb23c35a6593e84) for nginx 1.25.0

```
Changes with nginx 1.25.0                                        23 May 2023

    *) Feature: experimental HTTP/3 support.
```

The ngx_http_v3_module module (1.25.0) provides experimental support for [HTTP/3](https://datatracker.ietf.org/doc/html/rfc9114).
