### ISSUE TITLE
关于 nginx_dynamic_tls_records.patch 的兼容性问题

### ISSUE THREAD

**Issue by BROBIRD** [kn007/patch#29]
对于那些使用各类持续集成或自动化脚本编译较旧版本Nginx的用户，直接修改`nginx_dynamic_tls_records.patch` 的内容造成了一些“小混乱”，个人觉得为 `Nginx 1.27.2+` 版本单独发布一个 `nginx_dynamic_tls_records_1.27.2+.patch` 是不是更好？

**Comment by kn007** [comment]
使用原始版本地址，而非最新版本地址。
这是基础操作。

**Comment by SoftCreatR** [comment]
@kn007 The updated patch doesn't work in 1.27.4, I had to use the previous version, which works just fine.
