### ISSUE TITLE
请问如何启用 hpack？

### ISSUE THREAD

**Issue by wan-qy** [kn007/patch#3]
请问要启用 hpack 的话，只需在 configure 时添加 --with-http_v2_hpack_enc 参数即可，还是需要修改 nginx.conf ？
btw，如果对 SPDY 没有需求的话，patch 之后不添加编译选项是否可以取消对 SPDY 的支持？
THX！

**Comment by kn007** [comment]
不是有单纯hpack的patch么。。
在编译时加参数就行了。

用完整patch不加参数，不会添加功能。

**Comment by wan-qy** [comment]
有 Dynamic TLS Record 的需求2333

**Comment by kn007** [comment]
不加spdy参数就行了
