### ISSUE TITLE
`nginx.patch` is broken for nginx 1.15.3

### ISSUE THREAD

**Issue by CarterLi** [kn007/patch#7]
I saw those patches weren't updated for about 3 months. Will you updated them anymore?

**Comment by kn007** [comment]
I will update it later.

目前不兼容那个fix nginx hpack hpush patch，我需要重新整合，两者单独使用，是正常的。

**Comment by kn007** [comment]
Fix by https://github.com/kn007/patch/commit/ae756bd3676af84cce385e0b472a0ed634f74a52

**Comment by CarterLi** [comment]
Thanks for the patches!

> 然后最近天天加班

+1

**Comment by kn007** [comment]
@CarterLi 你可能需要重新下载patch编译下。。有个小地方忘记了
