### ISSUE TITLE
Is there hpack available for nginx 1.14.1  and 1.5.6?

### ISSUE THREAD

**Issue by kevin25** [kn007/patch#9]
Do you happen to have hpack for those versions?

**Comment by kn007** [comment]
For 1.14.1, you could test this one.

https://github.com/kn007/patch/raw/9af9838da8454cb0979bfd5431a21bde2c6173a1/nginx__1.13.10_http2_hpack.patch


Same as https://github.com/hakasenyang/openssl-patch/issues/11

**Comment by kevin25** [comment]
1.14.1 is the latest version. Can you please make sure it works with it?

**Comment by kn007** [comment]
`nginx.patch` for latest version.

you title had a mistake, 1.15.6, no 1.5.6.
